/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdicionarFotoRouteImport } from './routes/adicionar-foto'
import { Route as AdicionarHistoriaRouteImport } from './routes/adicionar-historia'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CriarMemoriaRouteImport } from './routes/criar-memoria'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MemoriasRouteImport } from './routes/memorias'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as EditarMemoriaIdRouteImport } from './routes/editar-memoria.$id'
import { Route as MemoriaIdRouteImport } from './routes/memoria.$id'
import { Route as PerfilIdRouteImport } from './routes/perfil.$id'
import { Route as UsuarioIdRouteImport } from './routes/usuario.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdicionarFotoRoute = AdicionarFotoRouteImport.update({
  id: '/adicionar-foto',
  path: '/adicionar-foto',
  getParentRoute: () => rootRouteImport,
} as any)
const AdicionarHistoriaRoute = AdicionarHistoriaRouteImport.update({
  id: '/adicionar-historia',
  path: '/adicionar-historia',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarMemoriaRoute = CriarMemoriaRouteImport.update({
  id: '/criar-memoria',
  path: '/criar-memoria',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriasRoute = MemoriasRouteImport.update({
  id: '/memorias',
  path: '/memorias',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const EditarMemoriaIdRoute = EditarMemoriaIdRouteImport.update({
  id: '/editar-memoria/$id',
  path: '/editar-memoria/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriaIdRoute = MemoriaIdRouteImport.update({
  id: '/memoria/$id',
  path: '/memoria/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilIdRoute = PerfilIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PerfilRoute,
} as any)
const UsuarioIdRoute = UsuarioIdRouteImport.update({
  id: '/usuario/$id',
  path: '/usuario/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adicionar-foto': typeof AdicionarFotoRoute
  '/adicionar-historia': typeof AdicionarHistoriaRoute
  '/cadastro': typeof CadastroRoute
  '/criar-memoria': typeof CriarMemoriaRoute
  '/explorar': typeof ExplorarRoute
  '/login': typeof LoginRoute
  '/memorias': typeof MemoriasRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/sobre': typeof SobreRoute
  '/editar-memoria/$id': typeof EditarMemoriaIdRoute
  '/memoria/$id': typeof MemoriaIdRoute
  '/perfil/$id': typeof PerfilIdRoute
  '/usuario/$id': typeof UsuarioIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adicionar-foto': typeof AdicionarFotoRoute
  '/adicionar-historia': typeof AdicionarHistoriaRoute
  '/cadastro': typeof CadastroRoute
  '/criar-memoria': typeof CriarMemoriaRoute
  '/explorar': typeof ExplorarRoute
  '/login': typeof LoginRoute
  '/memorias': typeof MemoriasRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/sobre': typeof SobreRoute
  '/editar-memoria/$id': typeof EditarMemoriaIdRoute
  '/memoria/$id': typeof MemoriaIdRoute
  '/perfil/$id': typeof PerfilIdRoute
  '/usuario/$id': typeof UsuarioIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adicionar-foto': typeof AdicionarFotoRoute
  '/adicionar-historia': typeof AdicionarHistoriaRoute
  '/cadastro': typeof CadastroRoute
  '/criar-memoria': typeof CriarMemoriaRoute
  '/explorar': typeof ExplorarRoute
  '/login': typeof LoginRoute
  '/memorias': typeof MemoriasRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/sobre': typeof SobreRoute
  '/editar-memoria/$id': typeof EditarMemoriaIdRoute
  '/memoria/$id': typeof MemoriaIdRoute
  '/perfil/$id': typeof PerfilIdRoute
  '/usuario/$id': typeof UsuarioIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adicionar-foto'
    | '/adicionar-historia'
    | '/cadastro'
    | '/criar-memoria'
    | '/explorar'
    | '/login'
    | '/memorias'
    | '/perfil'
    | '/sobre'
    | '/editar-memoria/$id'
    | '/memoria/$id'
    | '/perfil/$id'
    | '/usuario/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adicionar-foto'
    | '/adicionar-historia'
    | '/cadastro'
    | '/criar-memoria'
    | '/explorar'
    | '/login'
    | '/memorias'
    | '/perfil'
    | '/sobre'
    | '/editar-memoria/$id'
    | '/memoria/$id'
    | '/perfil/$id'
    | '/usuario/$id'
  id:
    | '__root__'
    | '/'
    | '/adicionar-foto'
    | '/adicionar-historia'
    | '/cadastro'
    | '/criar-memoria'
    | '/explorar'
    | '/login'
    | '/memorias'
    | '/perfil'
    | '/sobre'
    | '/editar-memoria/$id'
    | '/memoria/$id'
    | '/perfil/$id'
    | '/usuario/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdicionarFotoRoute: typeof AdicionarFotoRoute
  AdicionarHistoriaRoute: typeof AdicionarHistoriaRoute
  CadastroRoute: typeof CadastroRoute
  CriarMemoriaRoute: typeof CriarMemoriaRoute
  ExplorarRoute: typeof ExplorarRoute
  LoginRoute: typeof LoginRoute
  MemoriasRoute: typeof MemoriasRoute
  PerfilRoute: typeof PerfilRouteWithChildren
  SobreRoute: typeof SobreRoute
  EditarMemoriaIdRoute: typeof EditarMemoriaIdRoute
  MemoriaIdRoute: typeof MemoriaIdRoute
  UsuarioIdRoute: typeof UsuarioIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adicionar-foto': {
      id: '/adicionar-foto'
      path: '/adicionar-foto'
      fullPath: '/adicionar-foto'
      preLoaderRoute: typeof AdicionarFotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adicionar-historia': {
      id: '/adicionar-historia'
      path: '/adicionar-historia'
      fullPath: '/adicionar-historia'
      preLoaderRoute: typeof AdicionarHistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-memoria': {
      id: '/criar-memoria'
      path: '/criar-memoria'
      fullPath: '/criar-memoria'
      preLoaderRoute: typeof CriarMemoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memorias': {
      id: '/memorias'
      path: '/memorias'
      fullPath: '/memorias'
      preLoaderRoute: typeof MemoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editar-memoria/$id': {
      id: '/editar-memoria/$id'
      path: '/editar-memoria/$id'
      fullPath: '/editar-memoria/$id'
      preLoaderRoute: typeof EditarMemoriaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memoria/$id': {
      id: '/memoria/$id'
      path: '/memoria/$id'
      fullPath: '/memoria/$id'
      preLoaderRoute: typeof MemoriaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/$id': {
      id: '/perfil/$id'
      path: '/$id'
      fullPath: '/perfil/$id'
      preLoaderRoute: typeof PerfilIdRouteImport
      parentRoute: typeof PerfilRoute
    }
    '/usuario/$id': {
      id: '/usuario/$id'
      path: '/usuario/$id'
      fullPath: '/usuario/$id'
      preLoaderRoute: typeof UsuarioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PerfilRouteChildren {
  PerfilIdRoute: typeof PerfilIdRoute
}

const PerfilRouteChildren: PerfilRouteChildren = {
  PerfilIdRoute: PerfilIdRoute,
}

const PerfilRouteWithChildren =
  PerfilRoute._addFileChildren(PerfilRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdicionarFotoRoute: AdicionarFotoRoute,
  AdicionarHistoriaRoute: AdicionarHistoriaRoute,
  CadastroRoute: CadastroRoute,
  CriarMemoriaRoute: CriarMemoriaRoute,
  ExplorarRoute: ExplorarRoute,
  LoginRoute: LoginRoute,
  MemoriasRoute: MemoriasRoute,
  PerfilRoute: PerfilRouteWithChildren,
  SobreRoute: SobreRoute,
  EditarMemoriaIdRoute: EditarMemoriaIdRoute,
  MemoriaIdRoute: MemoriaIdRoute,
  UsuarioIdRoute: UsuarioIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
