/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdicionarFotoRouteImport } from './routes/adicionar-foto'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CriarMemoriaRouteImport } from './routes/criar-memoria'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MemoriasRouteImport } from './routes/memorias'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as MemoriaIdRouteImport } from './routes/memoria.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdicionarFotoRoute = AdicionarFotoRouteImport.update({
  id: '/adicionar-foto',
  path: '/adicionar-foto',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarMemoriaRoute = CriarMemoriaRouteImport.update({
  id: '/criar-memoria',
  path: '/criar-memoria',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriasRoute = MemoriasRouteImport.update({
  id: '/memorias',
  path: '/memorias',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriaIdRoute = MemoriaIdRouteImport.update({
  id: '/memoria/$id',
  path: '/memoria/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adicionar-foto': typeof AdicionarFotoRoute
  '/cadastro': typeof CadastroRoute
  '/criar-memoria': typeof CriarMemoriaRoute
  '/explorar': typeof ExplorarRoute
  '/login': typeof LoginRoute
  '/memorias': typeof MemoriasRoute
  '/perfil': typeof PerfilRoute
  '/sobre': typeof SobreRoute
  '/memoria/$id': typeof MemoriaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adicionar-foto': typeof AdicionarFotoRoute
  '/cadastro': typeof CadastroRoute
  '/criar-memoria': typeof CriarMemoriaRoute
  '/explorar': typeof ExplorarRoute
  '/login': typeof LoginRoute
  '/memorias': typeof MemoriasRoute
  '/perfil': typeof PerfilRoute
  '/sobre': typeof SobreRoute
  '/memoria/$id': typeof MemoriaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adicionar-foto': typeof AdicionarFotoRoute
  '/cadastro': typeof CadastroRoute
  '/criar-memoria': typeof CriarMemoriaRoute
  '/explorar': typeof ExplorarRoute
  '/login': typeof LoginRoute
  '/memorias': typeof MemoriasRoute
  '/perfil': typeof PerfilRoute
  '/sobre': typeof SobreRoute
  '/memoria/$id': typeof MemoriaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adicionar-foto'
    | '/cadastro'
    | '/criar-memoria'
    | '/explorar'
    | '/login'
    | '/memorias'
    | '/perfil'
    | '/sobre'
    | '/memoria/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adicionar-foto'
    | '/cadastro'
    | '/criar-memoria'
    | '/explorar'
    | '/login'
    | '/memorias'
    | '/perfil'
    | '/sobre'
    | '/memoria/$id'
  id:
    | '__root__'
    | '/'
    | '/adicionar-foto'
    | '/cadastro'
    | '/criar-memoria'
    | '/explorar'
    | '/login'
    | '/memorias'
    | '/perfil'
    | '/sobre'
    | '/memoria/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdicionarFotoRoute: typeof AdicionarFotoRoute
  CadastroRoute: typeof CadastroRoute
  CriarMemoriaRoute: typeof CriarMemoriaRoute
  ExplorarRoute: typeof ExplorarRoute
  LoginRoute: typeof LoginRoute
  MemoriasRoute: typeof MemoriasRoute
  PerfilRoute: typeof PerfilRoute
  SobreRoute: typeof SobreRoute
  MemoriaIdRoute: typeof MemoriaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adicionar-foto': {
      id: '/adicionar-foto'
      path: '/adicionar-foto'
      fullPath: '/adicionar-foto'
      preLoaderRoute: typeof AdicionarFotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-memoria': {
      id: '/criar-memoria'
      path: '/criar-memoria'
      fullPath: '/criar-memoria'
      preLoaderRoute: typeof CriarMemoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memorias': {
      id: '/memorias'
      path: '/memorias'
      fullPath: '/memorias'
      preLoaderRoute: typeof MemoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memoria/$id': {
      id: '/memoria/$id'
      path: '/memoria/$id'
      fullPath: '/memoria/$id'
      preLoaderRoute: typeof MemoriaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdicionarFotoRoute: AdicionarFotoRoute,
  CadastroRoute: CadastroRoute,
  CriarMemoriaRoute: CriarMemoriaRoute,
  ExplorarRoute: ExplorarRoute,
  LoginRoute: LoginRoute,
  MemoriasRoute: MemoriasRoute,
  PerfilRoute: PerfilRoute,
  SobreRoute: SobreRoute,
  MemoriaIdRoute: MemoriaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
